package org.videopocket.probe.resolver

import org.videopocket.probe.core.MediaInfo
import org.videopocket.probe.core.SubtitleTrack

enum class MediaType(val label: String, val arabicLabel: String) {
    VIDEO("Video", "فيديو"),
    AUDIO("Audio", "صوت"),
    IMAGE("Image", "صورة"),
    IMAGE_GALLERY("Gallery", "معرض صور"),
    GIF("GIF", "صورة متحركة"),
    STORY("Story", "قصة"),
    REEL("Reel", "ريلز"),
    SHORT_VIDEO("Short", "فيديو قصير"),
    POST("Post", "منشور"),
    PLAYLIST("Playlist", "قائمة تشغيل"),
    SUBTITLE("Subtitle", "ترجمة")
}

enum class ResolverErrorType(val defaultMessage: String, val defaultArabic: String) {
    INVALID_URL("Please enter a valid media URL.", "يرجى إدخال رابط وسائط صالح."),
    UNSUPPORTED_SOURCE("This media source or platform is not supported.", "هذا المصدر أو المنصة غير مدعومة حالياً."),
    MEDIA_NOT_FOUND("The requested media was not found or was removed.", "الوسائط المطلوبة غير موجودة أو تم حذفها."),
    PRIVATE_MEDIA("This media is private or requires authentication.", "هذا المحتوى خاص أو يتطلب تسجيل الدخول."),
    NO_VARIANTS("No downloadable media streams found.", "لم يتم العثور على صيغ قابلة للتنزيل."),
    NETWORK_ERROR("Network connection failed. Please check your connection.", "تعذر الاتصال بالشبكة. يرجى التحقق من اتصالك."),
    PROVIDER_CHANGED("This platform format may have changed. Please try again later.", "قد يكون هيكل المنصة تغير. يرجى المحاولة لاحقاً."),
    RATE_LIMITED("Request rate limit exceeded. Please wait a moment and try again.", "تم تجاوز حد الطلبات مؤقتاً. يرجى الانتظار والمحاولة لاحقاً."),
    PROCESSING_FAILED("Failed to process media metadata.", "فشلت معالجة بيانات الوسائط."),
    INSUFFICIENT_STORAGE("Insufficient device storage to process this media.", "مساحة التخزين غير كافية لمعالجة هذه الوسائط."),
    UNKNOWN("An unexpected error occurred while analyzing the link.", "حدث خطأ غير متوقع أثناء فحص الرابط.")
}

data class ResolverError(
    val type: ResolverErrorType,
    val detail: String? = null
) {
    fun userMessage(arabic: Boolean): String {
        return if (arabic) type.defaultArabic else type.defaultMessage
    }
}

data class MediaVariant(
    val id: String,
    val quality: String, // e.g. "1080p", "720p", "320kbps"
    val width: Int = 0,
    val height: Int = 0,
    val fps: Int = 0,
    val format: String, // "mp4", "webm", "mkv", "mp3", "m4a"
    val codec: String? = null,
    val audioCodec: String? = null,
    val bitrate: Int = 0,
    val fileSize: Long? = null,
    val videoUrl: String? = null,
    val audioUrl: String? = null,
    val requiresMerge: Boolean = false,
    val isAudioOnly: Boolean = false
) {
    val formattedSize: String? get() {
        val bytes = fileSize ?: return null
        if (bytes <= 0) return null
        val mb = bytes / (1024.0 * 1024.0)
        return if (mb >= 1000) String.format(java.util.Locale.US, "%.1f GB", mb / 1024.0)
        else String.format(java.util.Locale.US, "%.1f MB", mb)
    }
}

data class MediaSubtitle(
    val languageCode: String,
    val languageName: String,
    val format: String, // "srt", "vtt", "txt"
    val url: String,
    val isAutoGenerated: Boolean = false
)

data class MediaItem(
    val id: String,
    val title: String,
    val mediaType: MediaType,
    val url: String? = null,
    val thumbnailUrl: String? = null,
    val duration: Double? = null,
    val variants: List<MediaVariant> = emptyList(),
    val subtitles: List<MediaSubtitle> = emptyList()
)

data class NormalizedMetadata(
    val id: String,
    val canonicalUrl: String,
    val platform: String,
    val platformIcon: String,
    val title: String,
    val author: String? = null,
    val thumbnail: String? = null,
    val duration: Double? = null,
    val mediaType: MediaType = MediaType.VIDEO,
    val variants: List<MediaVariant> = emptyList(),
    val subtitles: List<MediaSubtitle> = emptyList(),
    val items: List<MediaItem> = emptyList(),
    val rawInfo: MediaInfo? = null
) {
    val heights: List<Int> get() = variants
        .filter { !it.isAudioOnly && it.height in 1..4320 }
        .map { it.height }
        .distinct()
        .sortedDescending()

    val defaultHeight: Int get() = heights.firstOrNull { it <= 1080 } ?: heights.minOrNull() ?: 1080

    val audioVariants: List<MediaVariant> get() = variants.filter { it.isAudioOnly }

    val videoVariants: List<MediaVariant> get() = variants.filter { !it.isAudioOnly }
}

sealed class MediaResolverResult {
    data class Success(val metadata: NormalizedMetadata) : MediaResolverResult()
    data class Failure(val error: ResolverError) : MediaResolverResult()
}
